/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import com.google.zxing.BinaryBitmap;
import com.google.zxing.LuminanceSource;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.NotFoundException;
import com.google.zxing.Result;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import dao.ConnectionProvider;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.Ellipse2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadFactory;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import utility.BDUtility;

/**
 *
 * @author HP
 */
public class MarkAttendance extends javax.swing.JFrame implements Runnable, ThreadFactory {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MarkAttendance.class.getName());

    private WebcamPanel panel = null;
    private Webcam webcam = null;
    private ExecutorService executor = Executors.newSingleThreadExecutor(this);
    private volatile boolean running = true;
    
    public MarkAttendance() {
        initComponents();
         BDUtility.setImage(this, "images/backImage.jpg", 1366, 768);
        this.getRootPane().setBorder(BorderFactory.createMatteBorder(4, 4, 4, 4, Color.orange));
        initWebcam();
        Timer timer = new Timer(1, e->updateTime());
        timer.start();
    }

    private void updateTime(){
      SimpleDateFormat simpleDateFormat = new SimpleDateFormat("YYYY-MM-dd HH:mm:ss.SSS");
      lblTime.setText(simpleDateFormat.format(new Date()));
      
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        webcamPanel = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblCheckInCheckOut = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Mark Attendance");

        btnExit.setBackground(new java.awt.Color(255, 153, 0));
        btnExit.setText("X");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        webcamPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Date");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Time");

        lblTime.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTime.setText("Time");

        lblCheckInCheckOut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(537, 537, 537)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(webcamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 858, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCheckInCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(183, 183, 183))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(27, 27, 27)
                        .addComponent(lblTime)
                        .addGap(84, 84, 84)
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCheckInCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(webcamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        running = false;
        stopWebcam();
        
        if(executor != null && !executor.isShutdown()){
           executor.shutdown();
        }
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MarkAttendance().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblCheckInCheckOut;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTime;
    private javax.swing.JPanel webcamPanel;
    // End of variables declaration//GEN-END:variables

    Map<String, String> resultMap = new HashMap<String, String>();
    
    @Override
    public void run() {
        do{
           try{
             Thread.sleep(1000);
           } catch(InterruptedException ex){
             
           }
           
           try{
              Result result = null;
              BufferedImage image = null;
              if(webcam.isOpen()){
                   if((image = webcam.getImage())== null){
                       continue;
                   }
              }
              
              LuminanceSource source = new BufferedImageLuminanceSource (image);
              BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));
              
              try{
                 result = new MultiFormatReader().decode(bitmap);
              } catch(NotFoundException ex){
                
              }
              
              if(result != null){
                 String jsonString = result.getText();
                 Gson gson = new Gson();
                 java.lang.reflect.Type type = new TypeToken<Map<String, String>>(){
                 
                 }.getType();
                 resultMap = gson.fromJson(jsonString, type);
                 
                 String finalPath = BDUtility.getPath("images\\" + resultMap.get("email")+".jpg");
                 CircularImageFrame(finalPath);
              }
           } catch(Exception ex){
             ex.printStackTrace();
           }
        } while(running);
    }

    @Override
    public Thread newThread(Runnable r) {
       Thread t = new Thread(r, "My Thread");
       t.setDaemon(true);
       return t;
    }
    
    private void stopWebcam(){
       if(webcam != null && webcam.isOpen()){
          webcam.close();
       }
    }

    private void initWebcam() {
        webcam = Webcam.getDefault();
        if(webcam != null){
          Dimension[] resolutions = webcam.getViewSizes();
          Dimension maxResolution = resolutions[resolutions.length-1];
          
          if(webcam.isOpen()){
            webcam.close();
          }
          
          webcam.setViewSize(maxResolution);
          webcam.open();
          
          panel = new WebcamPanel(webcam);
          panel.setPreferredSize(maxResolution);
          panel.setFPSDisplayed(true);
          
          webcamPanel.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0, 689,510));
          executor.execute(this);
          executor.shutdown();
        } else{
          System.out.println("Issue with webcam.");
        }
    }

    private BufferedImage imagee = null;
    private void CircularImageFrame(String imagePath) {
       try{
           Connection con = ConnectionProvider.getCon();
           Statement st = con.createStatement();
           ResultSet rs = st.executeQuery("select * from userdetails where email='" + resultMap.get("email")+"';");
           if(!rs.next()){
             showPopUpForCertainDuration("User is not Registered or Deleted", "Invalid QR", JOptionPane.ERROR_MESSAGE);
             return;
           }
           
           imagee = null;
           File imageFile = new File(imagePath);
           if(imageFile.exists()){
             try{
                imagee = ImageIO.read(new File (imagePath));
                imagee = createCircularImage(imagee);
                ImageIcon icon = new ImageIcon(imagee);
                lblImage.setIcon(icon);
             } catch(Exception ex){
               ex.printStackTrace();
             }
           } else{
              BufferedImage imageeee = new BufferedImage(300,300,BufferedImage.TYPE_INT_ARGB);
              Graphics2D g2d = imageeee.createGraphics();
              
              g2d.setColor(Color.black);
              g2d.fillOval(25, 25, 250, 250);
              
              g2d.setFont(new Font("serif",Font.BOLD, 250));
              g2d.setColor(Color.white);
              g2d.drawString(String.valueOf(resultMap.get("name").charAt(0)).toUpperCase(), 75, 225);
              g2d.dispose();
              
              ImageIcon imageIconn = new ImageIcon(imageeee);
              lblImage.setIcon(imageIconn);
              this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
              this.pack();
              this.setLocationRelativeTo(null);
              this.setVisible(true);
           }
           lblName.setHorizontalAlignment(JLabel.CENTER);
           lblName.setText(resultMap.get("name"));
           if(!checkInCheckOut()){
             return;
           }
       } catch(Exception ex){
          ex.printStackTrace();
       }
    }

    private void showPopUpForCertainDuration(String popUpMessage, String popUpHeader, Integer iconId) throws HeadlessException {
        final JOptionPane optionPane = new JOptionPane(popUpMessage, iconId);
        final JDialog dialog = optionPane.createDialog(popUpHeader);
        Timer timer = new Timer(5000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                 dialog.dispose();
                 clearUserDetails();
            }
        });
        timer.setRepeats(false);
        timer.start();
        dialog.setVisible(true);
    }
    
    private void clearUserDetails(){
        lblCheckInCheckOut.setText("");
        lblCheckInCheckOut.setBackground(null);
        lblCheckInCheckOut.setForeground(null);
        lblCheckInCheckOut.setOpaque(false);
        lblName.setText("");
        lblImage.setIcon(null);
        
    }

    private BufferedImage createCircularImage(BufferedImage imagee) {
      int diameter = 285;
      BufferedImage resizedImage = new BufferedImage(diameter, diameter, BufferedImage.TYPE_INT_ARGB);
      Graphics2D g2 = resizedImage.createGraphics();
      g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
      g2.drawImage(imagee, 0, 0, diameter, diameter, null);
      g2.dispose();
      BufferedImage circularImage = new BufferedImage(diameter,diameter,BufferedImage.TYPE_INT_ARGB);
      g2 = circularImage.createGraphics();
      Ellipse2D.Double circle = new Ellipse2D.Double(0,0,diameter, diameter);
      g2.setClip(circle);
      g2.drawImage(resizedImage, 0,0, null);
      g2.dispose();
      return circularImage;
    }

    private boolean checkInCheckOut() throws HeadlessException, SQLException {
        String popUpHeader = null;
        String popUpMessage = null;
        Color color = null;
        
        Connection con = ConnectionProvider.getCon();
        Statement st = con.createStatement();
        
        LocalDate currentDate = LocalDate.now();
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        
        LocalDateTime currentDateTime = LocalDateTime.now();
        DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        
        ResultSet rs = st.executeQuery("select * from userattendance where date='" + currentDate.format(dateFormatter) + "' and userid=" + Integer.valueOf(resultMap.get("id"))+";");
        
        Connection connection = ConnectionProvider.getCon();
        if(rs.next()){
           String checkoutDateTime = rs.getString(4);
           if(checkoutDateTime != null){
             popUpMessage = "Already CheckOut For the Day";
             popUpHeader = "Invalid CheckOut";
             showPopUpForCertainDuration(popUpMessage, popUpHeader, JOptionPane.ERROR_MESSAGE);
             return false;
           }
           
           String CheckInDateTime = rs.getString(3);
           LocalDateTime ChekInLocalDateTime = LocalDateTime.parse(CheckInDateTime, dateTimeFormatter);
           Duration duration = Duration.between(ChekInLocalDateTime, currentDateTime);
           
           long hours = duration.toHours();
           long minutes = duration.minusHours(hours).toMinutes();
           long seconds = duration.minusHours(hours).minusMinutes(minutes).getSeconds();
           
           if(!(hours>0 || (hours==0 && minutes>=2))){
               long remainingMinutes = 1 - minutes;
               long remainingSeconds = 60 - seconds;
               
               popUpMessage = String.format("Your work duration is less than 5 minutes\nYou can check out after: %d minutes and %d seconds", remainingMinutes, remainingSeconds);
               popUpHeader = "Duration Warning";
               
               showPopUpForCertainDuration(popUpMessage, popUpHeader, JOptionPane.WARNING_MESSAGE);
               return false;
           }
           String updateQuery = "update userattendance set checkout=?,workduration=? where date=? and userid=?";
           PreparedStatement preparedStatement = connection.prepareStatement(updateQuery);
           preparedStatement.setString(1,currentDateTime.format(dateTimeFormatter));
           preparedStatement.setString(2,"" + hours + "Hours and "+ minutes + " Minutes");
           preparedStatement.setString(3,currentDate.format(dateFormatter));
           preparedStatement.setString(4,resultMap.get("id"));
           
           preparedStatement.executeUpdate();
           popUpHeader = "CheckOut";
           popUpMessage = "Checked out at " + currentDateTime.format(dateTimeFormatter)  + "\nWork Duration " + hours + " Hours and" + minutes + "Minutes";
           color = Color.RED;
        } else {
            //CheckIn
            String insertQuery = "INSERT INTO userattendance (userid, date, checkin) VALUES(?,?,?)";
            PreparedStatement preparedStatement = connection.prepareStatement(insertQuery);
            preparedStatement.setString(1,resultMap.get("id"));
            preparedStatement.setString(2,currentDate.format(dateFormatter));
            preparedStatement.setString(3,currentDateTime.format(dateTimeFormatter));
            preparedStatement.executeUpdate();
            
            popUpHeader = "CheckIn";
           popUpMessage = "Check In at "+currentDateTime.format(dateTimeFormatter);
           color = Color.GREEN;
        }
        lblCheckInCheckOut.setHorizontalAlignment(JLabel.CENTER);
        lblCheckInCheckOut.setText(popUpHeader);
        lblCheckInCheckOut.setForeground(color);
        lblCheckInCheckOut.setBackground(Color.DARK_GRAY);
        lblCheckInCheckOut.setOpaque(true);
        showPopUpForCertainDuration(popUpMessage, popUpHeader, JOptionPane.INFORMATION_MESSAGE);
        return Boolean.TRUE;
    }
    
    @Override
    public void paint(Graphics g){
         super.paint(g);
         if(imagee != null){
            g.drawImage(imagee,0,0,null);
         }
    }
}
