/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import dao.ConnectionProvider;
import java.awt.Color;
import java.util.List;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.ZoneId;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utility.BDUtility;

/**
 *
 * @author HP
 */
public class ViewAttendance extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewAttendance.class.getName());

    /**
     * Creates new form ViewAttendance
     */
    public ViewAttendance() {
        initComponents();
        BDUtility.setImage(this, "images/backImage.jpg", 1114, 501);
        this.getRootPane().setBorder(BorderFactory.createMatteBorder(4, 4, 4, 4, Color.orange));
    
        jDateChooserFrom.setDateFormatString("yyyy-MM-dd");
        jDateChooserTo.setDateFormatString("yyyy-MM-dd");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        jDateChooserFrom = new com.toedter.calendar.JDateChooser();
        jDateChooserTo = new com.toedter.calendar.JDateChooser();
        txtSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblAbsent = new javax.swing.JLabel();
        presentLbl = new javax.swing.JLabel();
        absentLbl = new javax.swing.JLabel();
        lblPresent = new javax.swing.JLabel();
        CheckBoxContact = new javax.swing.JCheckBox();
        CheckBoxAddress = new javax.swing.JCheckBox();
        CheckBoxState = new javax.swing.JCheckBox();
        CheckBoxCountry = new javax.swing.JCheckBox();
        CheckBoxURI = new javax.swing.JCheckBox();
        btnResetFilter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1114, 501));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("View Attendance");

        btnExit.setBackground(new java.awt.Color(255, 153, 0));
        btnExit.setText("X");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblUser);

        jDateChooserFrom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jDateChooserFrom.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooserFromPropertyChange(evt);
            }
        });

        jDateChooserTo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jDateChooserTo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooserToPropertyChange(evt);
            }
        });

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel2.setText("On / From");

        jLabel3.setText("To");

        jLabel4.setText("Search");

        lblAbsent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAbsent.setForeground(new java.awt.Color(255, 0, 0));
        lblAbsent.setText("-----------");

        presentLbl.setText("Present");

        absentLbl.setText("Absent");

        lblPresent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPresent.setForeground(new java.awt.Color(0, 153, 0));
        lblPresent.setText("-----------");

        CheckBoxContact.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CheckBoxContact.setText("Contact");
        CheckBoxContact.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CheckBoxContactItemStateChanged(evt);
            }
        });

        CheckBoxAddress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CheckBoxAddress.setText("Address");
        CheckBoxAddress.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CheckBoxAddressItemStateChanged(evt);
            }
        });

        CheckBoxState.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CheckBoxState.setText("State");
        CheckBoxState.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CheckBoxStateItemStateChanged(evt);
            }
        });

        CheckBoxCountry.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CheckBoxCountry.setText("Country");
        CheckBoxCountry.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CheckBoxCountryItemStateChanged(evt);
            }
        });

        CheckBoxURI.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CheckBoxURI.setText("Unique Reg ID");
        CheckBoxURI.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CheckBoxURIItemStateChanged(evt);
            }
        });

        btnResetFilter.setBackground(new java.awt.Color(255, 153, 0));
        btnResetFilter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnResetFilter.setText("Reset Filters");
        btnResetFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetFilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(412, 412, 412)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(absentLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(presentLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPresent, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAbsent, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(CheckBoxContact, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CheckBoxAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CheckBoxState, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CheckBoxCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CheckBoxURI, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnResetFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserTo, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSearch)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserTo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooserFrom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(presentLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(absentLbl)
                            .addComponent(lblAbsent)))
                    .addComponent(lblPresent))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(CheckBoxContact)
                        .addGap(27, 27, 27)
                        .addComponent(CheckBoxAddress)
                        .addGap(33, 33, 33)
                        .addComponent(CheckBoxState)
                        .addGap(27, 27, 27)
                        .addComponent(CheckBoxCountry)
                        .addGap(28, 28, 28)
                        .addComponent(CheckBoxURI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnResetFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnResetFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetFilterActionPerformed
        txtSearch.setText("");
        jDateChooserFrom.setDate(null);
        jDateChooserTo.setDate(null);
        CheckBoxContact.setSelected(false);
        CheckBoxAddress.setSelected(false);
        CheckBoxState.setSelected(false);
        CheckBoxCountry.setSelected(false);
        CheckBoxURI.setSelected(false);
        
        loadDataInTable();
    }//GEN-LAST:event_btnResetFilterActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        loadDataInTable();
    }//GEN-LAST:event_formComponentShown

    private void CheckBoxContactItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CheckBoxContactItemStateChanged
        loadDataInTable();
    }//GEN-LAST:event_CheckBoxContactItemStateChanged

    private void CheckBoxAddressItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CheckBoxAddressItemStateChanged
        loadDataInTable();
    }//GEN-LAST:event_CheckBoxAddressItemStateChanged

    private void CheckBoxStateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CheckBoxStateItemStateChanged
       loadDataInTable();
    }//GEN-LAST:event_CheckBoxStateItemStateChanged

    private void CheckBoxCountryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CheckBoxCountryItemStateChanged
        loadDataInTable();
    }//GEN-LAST:event_CheckBoxCountryItemStateChanged

    private void CheckBoxURIItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CheckBoxURIItemStateChanged
        loadDataInTable();
    }//GEN-LAST:event_CheckBoxURIItemStateChanged

    private void jDateChooserFromPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooserFromPropertyChange
        loadDataInTable();
    }//GEN-LAST:event_jDateChooserFromPropertyChange

    private void jDateChooserToPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooserToPropertyChange
        loadDataInTable();
    }//GEN-LAST:event_jDateChooserToPropertyChange

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        loadDataInTable();
    }//GEN-LAST:event_txtSearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewAttendance().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxAddress;
    private javax.swing.JCheckBox CheckBoxContact;
    private javax.swing.JCheckBox CheckBoxCountry;
    private javax.swing.JCheckBox CheckBoxState;
    private javax.swing.JCheckBox CheckBoxURI;
    private javax.swing.JLabel absentLbl;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnResetFilter;
    private com.toedter.calendar.JDateChooser jDateChooserFrom;
    private com.toedter.calendar.JDateChooser jDateChooserTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAbsent;
    private javax.swing.JLabel lblPresent;
    private javax.swing.JLabel presentLbl;
    private javax.swing.JTable tblUser;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void loadDataInTable() {
       List <String> columns = new ArrayList<>(Arrays.asList(
           "ID","Name","Gender","Email","Date","CheckIn","CheckOut","Work Duration"
       ));
       
       String searchText = txtSearch.getText().toString();
       Date fromDateFromCal = jDateChooserFrom.getDate();
       LocalDate fromDate = null;
       if(fromDateFromCal != null){
         fromDate = fromDateFromCal.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
       }
       
       Date toDateFromCal = jDateChooserTo.getDate();
       LocalDate toDate = null;
       if(toDateFromCal != null){
         toDate = toDateFromCal.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
       }
       
       Long daysBetween = null;
       if(fromDate != null && toDate != null){
          daysBetween = countWeekdays(fromDate, toDate);
       }
       
       Boolean contactIncluded = CheckBoxContact.isSelected();
       Boolean addressIncluded = CheckBoxAddress.isSelected();
       Boolean stateIncluded = CheckBoxState.isSelected();
       Boolean countryIncluded = CheckBoxCountry.isSelected();
       Boolean uniqueRegIdIncluded = CheckBoxURI.isSelected();
       
       String sqlQuery = "SELECT ud.id, ud.name, ud.gender, ud.email, ua.date, ua.Checkin, ua.Checkout, ua.workduration ";
       if(contactIncluded){
          columns.add("Contact");
          sqlQuery += ", ud.contact";
       }
       
       if(addressIncluded){
          columns.add("Address");
          sqlQuery += ", ud.address";
        }
       
       if(stateIncluded){
          columns.add("State");
          sqlQuery += ", ud.state";
       }
       
       if(countryIncluded){
          columns.add("Country");
          sqlQuery += ", ud.country";
       }
       
       if(uniqueRegIdIncluded){
          columns.add("Unique Reg ID");
          sqlQuery += ", ud.uniqueregid";
       }
       
       sqlQuery += " FROM userdetails AS ud INNER JOIN userattendance AS ua ON ud.id = ua.userid ";
       if(searchText != null){
         sqlQuery += "where (ud.name like '%" + searchText + "%' or ud.email like '%"+ searchText + "%')";
         if(fromDate != null && toDate != null){
            sqlQuery += "AND ua.date BETWEEN '" + fromDate + "' AND '" + toDate + "'";
         } else if(fromDate != null){
            sqlQuery += " and ua.date = '" + fromDate + "'";
         }
       } else{
         if(fromDate != null && toDate != null){
           sqlQuery += " where ua.date BETWEEN '"  + fromDate + "' AND '" + toDate + "'";
         } else if(fromDate != null){
           sqlQuery += " where ua.date = '"  + fromDate + "'";
         }
       }
       
       DefaultTableModel model = new DefaultTableModel();
       model.setColumnIdentifiers(columns.toArray());
       tblUser.setModel(model);
       
       try{
           Connection con = ConnectionProvider.getCon();
           Statement st = con.createStatement();
           ResultSet rs = st.executeQuery(sqlQuery);
           Long presentCount = 0l;
           Long absentCount = 0l;
           Set<String> emailList = new HashSet<>();
           while (rs.next()){
             List<Object> row = new ArrayList<>();
             row.add(rs.getString("id"));
             row.add(rs.getString("name"));
             row.add(rs.getString("gender"));
             row.add(rs.getString("email"));
             emailList.add(rs.getString("email"));
             row.add(rs.getString("date"));
             row.add(rs.getString("checkin"));
             row.add(rs.getString("checkout"));
             row.add(rs.getString("workduration"));
             if(contactIncluded){
                row.add(rs.getString("contact"));
             }if(addressIncluded){
                row.add(rs.getString("address"));
             }
             if(stateIncluded){
                row.add(rs.getString("state"));
             }
             if(countryIncluded){
                row.add(rs.getString("country"));
             }
             if(uniqueRegIdIncluded){
                row.add(rs.getString("uniqueregid"));
             }
            
             if(rs.getString("checkout") == null){
                absentCount++;
             } else{
               presentCount++;
             }
             model.addRow(row.toArray());
           }
           
           if(emailList.size() == 1){
             lblPresent.setVisible(true);
             lblAbsent.setVisible(true);
             presentLbl.setVisible(true);
             absentLbl.setVisible(true);
             lblPresent.setText(presentCount.toString());
             if(daysBetween != null && daysBetween>0){
               absentCount = daysBetween - presentCount;
             }
             lblAbsent.setText(absentCount.toString());
           }else{
               lblPresent.setVisible(false);
               lblAbsent.setVisible(false);
               presentLbl.setVisible(false);
               absentLbl.setVisible(false);
           }
       }catch(Exception ex){
         JOptionPane.showMessageDialog(null, "something went wrong.");
       }
    }

    private Long countWeekdays(LocalDate start, LocalDate end) {
        long count = 0;
        LocalDate date = start;
        while(date.isBefore(end) || date.equals(end)){
            if(!(date.getDayOfWeek() == DayOfWeek.SATURDAY || date.getDayOfWeek() == DayOfWeek.SUNDAY)){
                 count++;
            }
            date = date.plusDays(1);
        }
        return count;
    }
}
